Attribute VB_Name = "模块4"
Sub button1()
  Call CopyDataA1
  Call CopyDataA2
  Call CopyDataA3
  Call CopyDataA4
  Call CopyDataA5
  Call CopyDataD2
  Call CopyDataD3
  Call CopyDataD4
  Call CopyDataD5
  Call CopyDataD6
  Call CopyDataD7
  Call CopyDataD8
  Call CopyDataD9
  Call CopyDataD10
  Call CopyDataD11
  Call CopyDataD12
  Call CopyDataD13
  Call CopyDataD14
  Call CopyDataD15
  Call CopyDataD16
  Call CopyDataD17
  Call CopyDataD18
  Call CopyDataD19
  Call CopyDataD20
  Call CopyDataE1
  Call CopyDataE2
  Call CopyDataE3
  Call CopyDataE4
  Call CopyDataE5
  Call CopyDataE6
  Call CopyDataE7
  Call CopyDataE8
  Call CopyDataE9
  Call CopyDataE10
  Call CopyDataF2
  Call CopyDataF3
  Call CopyDataF4
  Call CopyDataF5
  Call CopyDataF6
  Call CopyDataF7
  Call CopyDataF8
  Call CopyDataF9
  Call CopyDataF10
  Call CopyDataF11
  Call CopyDataF12
  Call CopyDataF13
  Call CopyDataF14
  Call CopyDataG1
  Call CopyDataG2
  Call CopyDataG3
  Call CopyDataG4
  Call CopyDataG5
  Call CopyDataG6
  Call CopyDataG11
  Call CopyDataG12
  Call CopyDataG13
  Call CopyDataG14
  Call CopyDataG15
  Call CopyDataG16
  Call CopyDataG17
  Call CopyDataH1
  Call CopyDataH2
  Call CopyDataJ1
  Call CopyDataJ2
  Call CopyDataJ13
  Call CopyDataK1
  Call CopyDataK2
  Call CopyDataQ1
  Call CopyDataQ2
  Call CopyDataQ3
  Call CopyDataQ4
  Call CopyDataQ5
  Call CopyDataQ6
  Call CopyDataQ7
  Call CopyDataU1
  Call CopyDataU2
  Call CopyDataU3
  Call CopyDataU4
  Call CopyDataU5
  Call CopyDataU6
  Call CopyDataY1
  Call CopyDataY2
  Call CopyDataY4
  MsgBox ("指派完成，请保存和关闭计算表")
End Sub
